[2023-03-18 23:49:05,064] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2023-03-17T00:00:00+00:00 [queued]>
[2023-03-18 23:49:05,075] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2023-03-17T00:00:00+00:00 [queued]>
[2023-03-18 23:49:05,076] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-18 23:49:05,077] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-03-18 23:49:05,078] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-18 23:49:05,093] {taskinstance.py:1377} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2023-03-17 00:00:00+00:00
[2023-03-18 23:49:05,100] {standard_task_runner.py:52} INFO - Started process 216 to run task
[2023-03-18 23:49:05,104] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2023-03-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmp_p7mku9l', '--error-file', '/tmp/tmpnw4r4ih3']
[2023-03-18 23:49:05,105] {standard_task_runner.py:80} INFO - Job 4: Subtask bigquery_external_table_task
[2023-03-18 23:49:05,124] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:525 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-03-18 23:49:05,172] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2023-03-17T00:00:00+00:00 [running]> on host 3c67d305fd30
[2023-03-18 23:49:05,260] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-17T00:00:00+00:00
[2023-03-18 23:49:05,263] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-03-18 23:49:05,264] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-18 23:49:05,958] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20230317T000000, start_date=20230318T234905, end_date=20230318T234905
[2023-03-18 23:49:06,007] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-18 23:49:06,044] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
